language: python
python:
  - "3.6"
  - "3.5"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
      conda env create --file environment.yml;
    else
      conda env create --file environment-35.yml;
    fi
  - source activate gridtools
  - python setup.py install

script:
  - export NUMBA_DISABLE_JIT=1
  - py.test -v --cov=gridtools test/
  - source deactivate
  - conda install conda-build anaconda-client
# did not work even though stated here https://conda.io/docs/user-guide/tasks/build-packages/variants.html#coupling-keys
#  - "conda build --old-build-string -c conda-forge -c numba -c anaconda recipe --variants \"{'python': ['3.5', '3.6']}\""
  - conda build --old-build-string -c conda-forge -c numba -c anaconda recipe

after_success:
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
  - RECIPE_OUTPUT=$(conda build --py $TRAVIS_PYTHON_VERSION --old-build-string -c conda-forge -c numba -c anaconda recipe --output)
  - anaconda -v -t $ANACONDA_TOKEN upload "$RECIPE_OUTPUT" -u cablab --force
