version: '0.4.1.{build}'

environment:
#  global:
      # Example can be found here https://github.com/quantopian/zipline/blob/master/appveyor.yml
#      ANACONDA_TOKEN: # not required anymore since it is configured at AppVeyor
  matrix:
    - PYTHON_LOC: "C:\\Miniconda37-x64"
      PYTHON_VERSION: 3.7
    - PYTHON_LOC: "C:\\Miniconda36-x64"
      PYTHON_VERSION: 3.6
    - PYTHON_LOC: "C:\\Miniconda35-x64"
      PYTHON_VERSION: 3.5

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda info -a

build_script:
  - cmd: conda env create --file environment.yml
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat gridtools
  - cmd: python setup.py install
  - cmd: conda list
  - cmd: py.test -v test
